language: node_js
node_js:
- '0.10'
- '0.11'
matrix:
 allow_failures:
   - node_js: "0.11"
before_install:
- gem install bundler
- bundle install
- npm install -g gulp
script:
- gulp ci
notifications:
  slack:
    secure: XJKDpEEcvdUdPgLFMG2htPp54HqGrDUxK1mffZPHzzgZNZR70Ma0n6ZqNeElx0uGf3Hhht2csmfE8+GQ4HvyZukQ6ZYUj8wT3D9W8wX/zJqItIvoLjToaYlKOAdLAlKfrByKt8qT23BuV/D8SlxPwGjrORNdtO/n/Sx4sxW5NJc=
